### ISSUE TITLE
OSError: [Errno 2]  for subprocess 

### ISSUE THREAD

**Issue by deter3** [kevincobain2000/jProcessing#4]
when try the samples in the help file with python 2.7 macbook air , 

>>> from jNlp.jConvert import *
>>> input_sentence = u'気象庁が２１日午前４時４８分、発表した天気概況によると、'
>>> print ' '.join(tokenizedRomaji(input_sentence))
>>> print tokenizedRomaji(input_sentence)

results was : 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.11-intel/egg/jNlp/jConvert.py", line 42, in tokenizedRomaji
  File "build/bdist.macosx-10.11-intel/egg/jNlp/jTokenize.py", line 42, in jReads
  File "build/bdist.macosx-10.11-intel/egg/jNlp/jCabocha.py", line 24, in cabocha
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by kevincobain2000** [comment]
hi, sorry I haven't been paying attention to this repo lately..
But a few troubleshooting steps if I recall,  you have cabocha and iconvert installed on  ur mac right..?

**Comment by kevincobain2000** [comment]
closing due to no response from the reporter

**Comment by deter3** [comment]
I had the same problem "File "build/bdist.macosx-10.11-intel/egg/jNlp/jCabocha.py", line 24, in cabocha " , I installed cabocha on mac by "brew install cabocha" . 

But error 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.11-intel/egg/jNlp/jTokenize.py", line 30, in jTokenize
  File "<string>", line 124, in XML
cElementTree.ParseError: not well-formed (invalid token): line 1, column 4

I do not know what's  iconvert , can you advise where I can installed ?(googled and can hardly find it )

**Comment by kevincobain2000** [comment]
sorry it is called ``iconv``

```
➜  ~ type iconv
iconv is /usr/bin/iconv
```
